Repository SSAFY-10th-Seoul17/algorithm_ssafy, pull requests merged in 2023-08, with the labels that each got.

#30 최준호 / 8월 1주차 / 월
  ChoiJunHo/BOJ/boj02447.java
Labels: Review plz

#23 엄소현 / 7월 4주차 / 목
  EomSoHyun/BOJ/boj14606.java
  EomSoHyun/BOJ/boj17484.java
  EomSoHyun/BOJ/boj1992.java
  EomSoHyun/BOJ/boj4779.java
Labels: Review plz

#35 차재환 / 8월 1주차 / 월
  ChaJaeHwan/boj/boj1992.java
  ChaJaeHwan/boj/boj4779.java
Labels: Review plz

#34 나호균 / 8월 1주차 / 월
  Nahokyun/boj/boj1992.java
  Nahokyun/boj/boj2447.java
  Nahokyun/boj/boj4779.java
Labels: Review plz, Question

#39 황진하 / 8월 1주차 / 월
  HwangJinHa/BOJ/boj10422.java
  HwangJinHa/BOJ/boj11729.java
  HwangJinHa/BOJ/boj1436.java
  HwangJinHa/BOJ/boj14500.java
  HwangJinHa/BOJ/boj14502.java
  HwangJinHa/BOJ/boj1992.java
  HwangJinHa/BOJ/boj2447.java
  HwangJinHa/BOJ/boj2503.java
  HwangJinHa/BOJ/boj2508.java
  HwangJinHa/BOJ/boj4779.java
Labels: Review plz, Question

#47 임예준 / 8월 1주차 / 월
  dpwns/boj/boj1992.java
  dpwns/boj/boj4779.java
Labels: Review plz

#53 나호균 / 8월 1주차 / 목
  Nahokyun/boj/boj11729.java
  Nahokyun/boj/boj1436.java
  Nahokyun/boj/boj14500.java
  Nahokyun/boj/boj14502.java
  Nahokyun/boj/boj2503.java
  Nahokyun/boj/boj2508.java
Labels: Question

#56 차재환 / 8월 1주차 / 목
  ChaJaeHwan/boj/boj11729.java
  ChaJaeHwan/boj/boj1992.java
  ChaJaeHwan/boj/boj2503.java
  ChaJaeHwan/boj/boj4779.java
Labels: Review plz, Question

#61 소재열 / 8월 1주차 / 목
  jaeyeol/boj/Boj11729.java
  jaeyeol/boj/Boj1436.java
  jaeyeol/boj/Boj14500.java
  jaeyeol/boj/Boj14502.java
  jaeyeol/boj/Boj2503.java
  jaeyeol/boj/Boj2508.java
Labels: Review plz

#57 임예준 / 8월 1주차 / 목
  dpwns/boj/boj11729.java
  dpwns/boj/boj1436.java
  dpwns/boj/boj14500.java
  dpwns/boj/boj14502.java
  dpwns/boj/boj2503.java
  dpwns/boj/boj2508.java
Labels: Review plz

#78 최준호 / 8월 2주차 / 월
  ChoiJunHo/BOJ/study04_brute_force/boj01436.java
  ChoiJunHo/BOJ/study04_brute_force/boj02503.java
  ChoiJunHo/BOJ/study04_brute_force/boj02508.java
  ChoiJunHo/BOJ/study04_brute_force/boj11729.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj01325.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj01697.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj02004.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj10972.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj10973.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj10974.java
  ChoiJunHo/BOJ/study05_permutation_combination/boj24230.java
Labels: Review plz

#72 황진하 / 8월 2주차 / 월
  HwangJinHa/BOJ/boj10972.java
  HwangJinHa/BOJ/boj10973.java
  HwangJinHa/BOJ/boj10974.java
  HwangJinHa/BOJ/boj1325.java
  HwangJinHa/BOJ/boj1697.java
  HwangJinHa/BOJ/boj2004.java
  HwangJinHa/BOJ/boj24230.java
Labels: fail

#68 이현진 / 8월 2주차 / 월
  LeeHyeonJin/BOJ/boj10972.java
  LeeHyeonJin/BOJ/boj10973.java
  LeeHyeonJin/BOJ/boj10974.java
  LeeHyeonJin/BOJ/boj1325.java
  LeeHyeonJin/BOJ/boj1697.java
  LeeHyeonJin/BOJ/boj2004.java
  LeeHyeonJin/BOJ/boj24230.java
Labels: Question

#80 김미서 / 8월 2주차 / 월
  KimMiSeo/BOJ/BOJ10972_다음순열.java
  KimMiSeo/BOJ/BOJ10973_이전순열.java
  KimMiSeo/BOJ/BOJ10974_모든순열.java
  KimMiSeo/BOJ/BOJ1325_효율적인해킹.java
  KimMiSeo/BOJ/BOJ2004_조합0의개수.java
  KimMiSeo/BOJ/BOJ24230_트리색칠하기.java
Labels: CounterExample

#85 최준호 / 8월 2주차 / 목
  ChoiJunHo/BOJ/study06_BFS_DFS/boj01167.java
  ChoiJunHo/BOJ/study06_BFS_DFS/boj02210.java
  ChoiJunHo/BOJ/study06_BFS_DFS/boj05014.java
  ChoiJunHo/BOJ/study06_BFS_DFS/boj05427.java
  ChoiJunHo/BOJ/study06_BFS_DFS/boj06593.java
  ChoiJunHo/BOJ/study06_BFS_DFS/boj14716.java
Labels: Review plz

#88 소재열 / 8월 2주차 / 목
  jaeyeol/boj/Boj01167.java
  jaeyeol/boj/Boj05014.java
  jaeyeol/boj/Boj06593.java
  jaeyeol/boj/Boj14716.java
  jaeyeol/boj/Boj2210.java
  jaeyeol/boj/Boj5427.java
Labels: Review plz, JAVA GOD

#90 이태호 / 8월 2주차 / 목
  LeeTaeHo/boj/boj14716.java
  LeeTaeHo/boj/boj2210.java
  LeeTaeHo/boj/boj5014.java
  LeeTaeHo/boj/boj6593.java
Labels: Review plz, I'm TaeHO

#75 이승헌 / 8월 2주차 / 월, 목
  LeeSeungheon/boj/boj10972.java
  LeeSeungheon/boj/boj1167.java
  LeeSeungheon/boj/boj1325.java
  LeeSeungheon/boj/boj14716.java
  LeeSeungheon/boj/boj2210.java
  LeeSeungheon/boj/boj5014.java
  LeeSeungheon/boj/boj5427.java
  LeeSeungheon/boj/boj6593.java
Labels: Review plz

#89 임예준 / 8월 2주차 / 목
  dpwns/boj/boj1167.java
  dpwns/boj/boj14716.java
  dpwns/boj/boj2210.java
  dpwns/boj/boj5014.java
  dpwns/boj/boj5427.java
  dpwns/boj/boj6593.java
Labels: Review plz

#73 차재환 / 8월 2주차 / 월 , 목
  ChaJaeHwan/boj/boj1325.java
  ChaJaeHwan/boj/boj14716.java
  ChaJaeHwan/boj/boj2004.java
  ChaJaeHwan/boj/boj2210.java
  ChaJaeHwan/boj/boj5014.java
  ChaJaeHwan/boj/boj5427.java
  ChaJaeHwan/boj/boj6593.java
Labels: Review plz

#113 임예준 / 8월 3주차 / 월
  dpwns/boj/boj17086.java
  dpwns/boj/boj18353.java
  dpwns/boj/boj2624.java
Labels: Review plz, Fail

#103 이태호 / 8월 3주차 / 월
  LeeTaeHo/boj/boj16401.java
  LeeTaeHo/boj/boj17086.java
  LeeTaeHo/boj/boj18353.java
  LeeTaeHo/boj/boj7795.java
Labels: Review plz, I'm TaeHO

#121 남희수 / 8월 3주차 / 목
  HeesuNam/boj/boj11058.java
  HeesuNam/boj/boj16401.java
  HeesuNam/boj/boj7795.java
Labels: Review plz

#112 차재환 / 8월 3주차 / 월, 목
  ChaJaeHwan/boj/boj11058.java
  ChaJaeHwan/boj/boj16401.java
  ChaJaeHwan/boj/boj17086.java
  ChaJaeHwan/boj/boj18353.java
  ChaJaeHwan/boj/boj7795.java
Labels: Review plz, Fail

#124 임예준 / 8월 3주차 / 목
  dpwns/boj/boj11058.java
  dpwns/boj/boj16401.java
  dpwns/boj/boj7795.java
Labels: Review plz

#123 최준호 / 8월 3주차 / 목
  ChoiJunHo/BOJ/week08_Binary_Search/boj07795.java
  ChoiJunHo/BOJ/week08_Binary_Search/boj11058.java
  ChoiJunHo/BOJ/week08_Binary_Search/boj13397.java
  ChoiJunHo/BOJ/week08_Binary_Search/boj16401.java
  ChoiJunHo/BOJ/week09_Graph/boj03184.java
  ChoiJunHo/BOJ/week09_Graph/boj05567.java
  ChoiJunHo/BOJ/week09_Graph/boj13424.java
  ChoiJunHo/BOJ/week09_Graph/boj14284.java
  ChoiJunHo/BOJ/week09_Graph/boj15802.txt
Labels: Review plz, A준

#134 임예준 / 8월 4주차 / 월
  dpwns/boj/boj13424.java
  dpwns/boj/boj14284.java
  dpwns/boj/boj15971.java
  dpwns/boj/boj3184.java
  dpwns/boj/boj5567.java
Labels: Review plz

#155 김승우 / 8월 4주차 / 목
  Kimseungwoo/boj/boj14567.java
  Kimseungwoo/boj/boj18243.java
  Kimseungwoo/boj/boj8394.java
Labels: Review plz

#169 이태호 / 8월 5주차 / 월
  LeeTaeHo/boj/boj14497.java
Labels: I'm TaeHO

#170 임예준 / 8월 5주차 / 월
  dpwns/boj/boj16198.java
  dpwns/boj/boj17265.java
  dpwns/boj/boj1802.java
Labels: Review plz
